# Generated by Django 4.2.23 on 2025-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture of the user",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
