# Generated by Django 4.2.23 on 2025-10-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("seller", "Seller"),
                    ("service_provider", "Service Provider"),
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                ],
                db_index=True,
                default="buyer",
                help_text="User role in the marketplace",
                max_length=30,
            ),
        ),
    ]
