# Generated by Django 4.2.23 on 2025-10-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, help_text="Phone number", max_length=30),
        ),
    ]
