# Generated by Django 4.2.23 on 2025-10-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("registration", "Registration"), ("login", "Login")],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "one_time_passwords",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "used"],
                        name="one_time_pa_email_1688d0_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="one_time_pa_expires_48c309_idx"
                    ),
                ],
            },
        ),
    ]
