# Generated by Django 4.2.23 on 2026-04-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_full_name_onetimepassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en_us", "English (American)"),
                            ("en_gb", "English (British)"),
                        ],
                        default="en_us",
                        max_length=10,
                    ),
                ),
                ("interested_categories", models.JSONField(blank=True, default=list)),
                ("email_newsletter", models.BooleanField(default=True)),
                ("email_promotions", models.BooleanField(default=True)),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_unsubscribe_all", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="DeliveryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_person", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "address",
                    models.TextField(
                        help_text="Delivery address / offshore coordinates"
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(max_length=30)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "delivery_details",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
