# Generated by Django 4.2.23 on 2026-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_usertwofactor_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="preferred_currency",
            field=models.CharField(default="NGN", max_length=10),
        ),
    ]
