# Generated by Django 4.2.23 on 2026-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userpreference_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='government_id',
            field=models.FileField(blank=True, help_text='Government-issued ID document', null=True, upload_to='verification/government_ids/'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
