# Generated by Django 4.2.23 on 2026-04-08 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_alter_category_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug of the store", max_length=255, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the store", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The description of the store", null=True
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="The banner image of the store",
                        null=True,
                        upload_to="store/banners/",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="The logo of the store",
                        null=True,
                        upload_to="store/logos/",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The email of the store",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="The phone number of the store",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="The address of the store", null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="The city of the store",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="The state of the store",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="The country of the store",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        help_text="The zip code of the store",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("policy", models.TextField(help_text="The policy of the store")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the store is active"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether the store is published"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The last updated time of the store"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The creation time of the store"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="The categories of the store",
                        limit_choices_to={"is_active": True},
                        related_name="stores",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user who owns the store",
                        limit_choices_to={"role": "seller"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
