# Generated by Django 4.2.23 on 2026-04-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the store is verified"
            ),
        ),
    ]
