# Generated by Django 4.2.23 on 2026-04-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_store_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Platform commission percentage charged on sales",
                max_digits=5,
            ),
        ),
    ]
