# Generated by Django 4.2.23 on 2026-05-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_storeactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_name", models.CharField(max_length=255)),
                ("carrier_name", models.CharField(max_length=255)),
                ("delivery_time_min", models.PositiveIntegerField()),
                ("delivery_time_max", models.PositiveIntegerField()),
                (
                    "flat_rate_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_profiles",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "db_table": "shipping_profiles",
            },
        ),
    ]
