# Generated by Django 4.2.23 on 2026-04-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(upload_to="categories/images/"),
        ),
    ]
