# Generated by Django 4.2.23 on 2026-04-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_url",
            field=models.URLField(
                blank=True, help_text="External icon URL if not uploading file"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Category icon image",
                null=True,
                upload_to="categories/images/",
            ),
        ),
    ]
