# Generated by Django 4.2.23 on 2025-10-10 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0003_alter_listingdocument_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Inquiry subject", max_length=200),
                ),
                ("message", models.TextField(help_text="Inquiry message")),
                (
                    "contact_name",
                    models.CharField(help_text="Inquirer contact name", max_length=100),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Inquirer contact email", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Inquirer contact phone", max_length=20
                    ),
                ),
                (
                    "contact_company",
                    models.CharField(
                        blank=True, help_text="Inquirer company", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        default="pending",
                        help_text="Inquiry status",
                        max_length=20,
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False, help_text="Whether this is marked as urgent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the inquiry was first read",
                        null=True,
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the inquiry was replied to",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of inquirer", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent of inquirer"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User who sent the inquiry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="The listing this inquiry is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="listings.listing",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User who received the inquiry (listing owner)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "db_table": "inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Reply message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        help_text="The inquiry this reply belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who sent the reply",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Reply",
                "verbose_name_plural": "Inquiry Replies",
                "db_table": "inquiry_replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file", upload_to="inquiries/attachments/"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        help_text="The inquiry this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Attachment",
                "verbose_name_plural": "Inquiry Attachments",
                "db_table": "inquiry_attachments",
            },
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["listing", "-created_at"], name="inquiries_listing_f1c740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["from_user", "-created_at"], name="inquiries_from_us_2a82db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["to_user", "-created_at"], name="inquiries_to_user_a91734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["status", "-created_at"], name="inquiries_status_e86e34_idx"
            ),
        ),
    ]
