# Generated by Django 4.2.23 on 2025-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Inquirer contact phone", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("read", "Read"),
                    ("replied", "Replied"),
                    ("closed", "Closed"),
                    ("spam", "Spam"),
                ],
                default="pending",
                help_text="Inquiry status",
                max_length=30,
            ),
        ),
    ]
