# Generated by Django 4.2.23 on 2026-04-24 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0007_alter_listing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commerce", "0005_dispute"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("certification", "Certification"),
                            ("insurance", "Insurance"),
                            ("license", "License"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "party_role",
                    models.CharField(
                        choices=[("buyer", "Buyer"), ("vendor", "Vendor")],
                        default="vendor",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/documents/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expiring", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                            ("included", "Included"),
                            ("pending", "Pending Review"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_documents",
                        to="listings.listing",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_documents",
                        to="commerce.order",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_compliance_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="compliance__status_9261b5_idx",
                    ),
                    models.Index(
                        fields=["document_type", "-created_at"],
                        name="compliance__documen_dedd4c_idx",
                    ),
                    models.Index(
                        fields=["end_date"], name="compliance__end_dat_2f4ca1_idx"
                    ),
                ],
            },
        ),
    ]
