# Generated by Django 4.2.23 on 2025-09-16 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Listing image", upload_to="listings/images/"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="Image caption", max_length=200
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary image"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Image",
                "verbose_name_plural": "Listing Images",
                "db_table": "listing_images",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ListingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Listing document", upload_to="listings/documents/"
                    ),
                ),
                ("name", models.CharField(help_text="Document name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Document description"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Document",
                "verbose_name_plural": "Listing Documents",
                "db_table": "listing_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_records",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing View",
                "verbose_name_plural": "Listing Views",
                "db_table": "listing_views",
                "indexes": [
                    models.Index(
                        fields=["listing", "-viewed_at"],
                        name="listing_vie_listing_d8c931_idx",
                    ),
                    models.Index(
                        fields=["-viewed_at"], name="listing_vie_viewed__dbdaff_idx"
                    ),
                ],
            },
        ),
    ]
