# Generated by Django 4.2.23 on 2025-09-16 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_listingimage_listingdocument_listingview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingdocument",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="listingimage",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="listingview",
            options={"ordering": ["-viewed_at"]},
        ),
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listing",
            name="inquiries_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="listing",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="negotiable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price_unit",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="service_area",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="listing",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="SEO-friendly URL", max_length=220, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="state_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("flagged", "Flagged"),
                    ("suspended", "Suspended"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listingdocument",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="listingdocument",
            name="document",
            field=models.FileField(upload_to="listings/documents/"),
        ),
        migrations.AlterField(
            model_name="listingdocument",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listingdocument",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(upload_to="listings/images/"),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
