# Generated by Django 4.2.23 on 2025-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listingdocument_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price_unit",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("flagged", "Flagged"),
                    ("suspended", "Suspended"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
