# Generated by Django 4.2.23 on 2026-04-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        (
            "listings",
            "0004_alter_listing_condition_alter_listing_contact_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The store that the listing belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="store.store",
            ),
        ),
    ]
