# Generated by Django 4.2.23 on 2026-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_saveditem_saveditem_unique_saved_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("paused", "Paused"),
                    ("archived", "Archived"),
                    ("flagged", "Flagged"),
                    ("suspended", "Suspended"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
