# Generated by Django 4.2.23 on 2026-07-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="currency",
            field=models.CharField(
                default="USD", help_text="Currency code (USD as base)", max_length=3
            ),
        ),
    ]
