# Generated by Django 4.2.23 on 2026-04-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("rental_approved", "Rental Approved"),
                            ("ready_for_dispatch", "Ready for Dispatch"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("rental_period_active", "Rental Period Active"),
                            ("rental_period_ending", "Rental Period Ending Soon"),
                            ("rental_extended", "Rental Extended"),
                            ("equipment_collected", "Equipment Collected"),
                            ("vendor_confirmed_return", "Vendor Confirmed Return"),
                            ("order_completed", "Order Completed"),
                            ("order_cancelled", "Order Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="commerce.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
