# Generated by Django 4.2.23 on 2026-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_orderactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="vendor_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes from the vendor to the buyer"
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="vendor_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Vendor's counter-offer price (overrides listing price for this quote)",
                max_digits=14,
                null=True,
            ),
        ),
    ]
