# Generated by Django 4.2.23 on 2026-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_dispute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_payment", "Pending payment"),
                    ("paid", "Paid"),
                    ("order_confirmed", "Order Confirmed"),
                    ("item_dispatched", "Item Dispatched"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("active_hire", "Active Hire"),
                    ("hire_ended", "Hire Ended"),
                    ("item_returned", "Item Returned"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="orderactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order_placed", "Order Placed"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("rental_approved", "Rental Approved"),
                    ("ready_for_dispatch", "Ready for Dispatch"),
                    ("shipped", "Shipped"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("rental_period_active", "Rental Period Active"),
                    ("rental_period_ending", "Rental Period Ending Soon"),
                    ("rental_extended", "Rental Extended"),
                    ("equipment_collected", "Equipment Collected"),
                    ("vendor_confirmed_return", "Vendor Confirmed Return"),
                    ("order_completed", "Order Completed"),
                    ("order_cancelled", "Order Cancelled"),
                    ("payment_received", "Payment Received"),
                    ("order_confirmed", "Order Confirmed"),
                    ("item_dispatched", "Item Dispatched"),
                    ("hire_started", "Rental Started"),
                    ("hire_ended", "Rental Ended"),
                    ("item_returned", "Item Returned"),
                    ("order_fulfilled", "Order Fulfilled"),
                    ("dispute_opened", "Dispute Opened"),
                    ("dispute_resolved", "Dispute Resolved"),
                    ("order_refunded", "Order Refunded"),
                    ("other", "Other Event"),
                ],
                max_length=50,
            ),
        ),
    ]
