# Generated by Django 4.2.23 on 2026-07-03 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_status'),
        ('accounts', '0011_verificationrequest_government_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0006_alter_order_status_alter_orderactivity_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quote_request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='vendor_price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivery_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='accounts.deliverydetail'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='locked_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Locked contract price from a quote (bypasses unit_price × qty)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='commerce.quoterequest'),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='adjustments',
            field=models.JSONField(blank=True, default=list, help_text='List of adjustments (name, amount, type: addition|subtraction)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='accounts.deliverydetail'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard calculated price before adjustments', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('buy', 'Buy transaction'), ('hire', 'Hire booking'), ('lease', 'Lease contract')], max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.deliverydetail')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='listings.listing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.quoterequest')),
            ],
            options={
                'db_table': 'commerce_order_items',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkout_sessions',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='commerce.checkoutsession'),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='commerce.checkoutsession'),
        ),
    ]
