# Generated by Django 4.2.23 on 2026-07-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0007_remove_order_listing_remove_order_quote_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
