# Generated by Django 4.2.23 on 2026-08-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_checkoutsession_currency_alter_order_currency_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='commerce_or_order_t_cb65e2_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_scheduled_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rental_duration_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rental_end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rental_start_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
