# Generated by Django 4.2.23 on 2026-04-24 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_storeactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financials", "0002_vendorearning_payout"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pending_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="store.store",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vendor_wallets",
            },
        ),
        migrations.AddField(
            model_name="vendorearning",
            name="is_disputed",
            field=models.BooleanField(
                default=False,
                help_text="If true, funds cannot be moved to available or paid out",
            ),
        ),
        migrations.AlterField(
            model_name="vendorearning",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("available", "Available"),
                    ("processing", "Processing Payout"),
                    ("paid_out", "Paid Out"),
                    ("reversed", "Reversed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earning", "Earning Credit"),
                            ("payout", "Payout Debit"),
                            ("refund", "Refund/Reversal"),
                            ("adjustment", "Manual Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(max_length=255)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the related object (Order, Payout, etc.)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="financials.vendorwallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
