# Generated by Django 4.2.23 on 2026-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_vendorwallet_vendorearning_is_disputed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('frozen', 'Frozen')], db_index=True, default='requested', max_length=20),
        ),
    ]
