# Generated by Django 4.2.23 on 2026-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportticket",
            name="dispute_amount",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="dispute_reason",
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("support", "Support")],
                db_index=True,
                default="support",
                max_length=20,
            ),
        ),
    ]
