# Generated by Django 4.2.23 on 2026-04-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_seed_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("revoked", "Revoked"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminprofile",
            name="staff_role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("operations_admin", "Operations admin"),
                    ("finance_admin", "Finance admin"),
                    ("support_admin", "Support admin"),
                    ("compliance_admin", "Compliance Admin"),
                    ("read_only", "Read only"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("overview_dashboard", "Overview Dashboard"),
                    ("listings_management", "Listings management"),
                    ("orders_bookings", "Orders & Bookings"),
                    ("vendors_onboarding", "Vendors & onboarding"),
                    ("payments_finance", "Payments & finance"),
                    ("compliance_contracts", "Compliance & Contracts"),
                    ("supports", "Supports"),
                    ("analytics", "Analytics"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("operations_admin", "Operations admin"),
                    ("finance_admin", "Finance admin"),
                    ("support_admin", "Support admin"),
                    ("compliance_admin", "Compliance Admin"),
                    ("read_only", "Read only"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
