# Generated by Django 4.2.23 on 2026-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_alter_adminprofile_invite_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("content_reviewed", "Content Reviewed"),
                    ("content_resolved", "Content Resolved"),
                    ("content_dismissed", "Content Dismissed"),
                    ("report_submitted", "Report Submitted"),
                    ("user_verified", "User Verified"),
                    ("user_rejected", "User Rejected"),
                    ("user_banned", "User Banned"),
                    ("user_unbanned", "User Unbanned"),
                    ("admin_invited", "Admin Invited"),
                    ("admin_revoked", "Admin Revoked"),
                    ("admin_activated", "Admin Activated"),
                    ("listing_published", "Listing Published"),
                    ("listing_archived", "Listing Archived"),
                    ("listing_removed", "Listing Removed"),
                    ("listing_featured", "Listing Featured"),
                    ("bulk_action_performed", "Bulk Action Performed"),
                    ("roles_matrix_updated", "Roles Matrix Updated"),
                    ("verification_approved", "Verification Approved"),
                    ("verification_rejected", "Verification Rejected"),
                ],
                max_length=50,
            ),
        ),
    ]
