# Generated by Django 4.2.23 on 2026-04-24 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0005_alter_adminactionlog_action_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_buy", models.BooleanField(default=True)),
                ("enable_rent", models.BooleanField(default=True)),
                ("enable_services", models.BooleanField(default=False)),
                ("vendor_approval_required", models.BooleanField(default=True)),
                ("listing_approval_required", models.BooleanField(default=True)),
                ("default_currency", models.CharField(default="NGN", max_length=10)),
                ("timezone", models.CharField(default="Africa/Lagos", max_length=50)),
                ("date_format", models.CharField(default="DD/MM/YY", max_length=20)),
                ("force_password_reset", models.BooleanField(default=False)),
                ("session_timeout", models.BooleanField(default=True)),
                ("notify_new_vendor_signup", models.BooleanField(default=True)),
                ("notify_new_dispute", models.BooleanField(default=True)),
                ("notify_contract_expiring", models.BooleanField(default=False)),
                ("notify_failed_payment", models.BooleanField(default=False)),
                ("channel_in_app", models.BooleanField(default=True)),
                ("channel_email", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "platform_config",
            },
        ),
    ]
