# Generated by Django 4.2.23 on 2026-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_platformconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("application_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "job_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("overview_dashboard", "Overview Dashboard"),
                    ("listings_management", "Listings management"),
                    ("orders_bookings", "Orders & Bookings"),
                    ("vendors_onboarding", "Vendors & onboarding"),
                    ("payments_finance", "Payments & finance"),
                    ("compliance_contracts", "Compliance & Contracts"),
                    ("supports", "Supports"),
                    ("analytics", "Analytics"),
                    ("messages_monitoring", "Messages Monitoring"),
                    ("careers", "Careers"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
