# Generated by Django 4.2.23 on 2026-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_joblisting_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('overview_dashboard', 'Overview Dashboard'), ('listings_management', 'Listings management'), ('orders_bookings', 'Orders & Bookings'), ('vendors_onboarding', 'Vendors & onboarding'), ('payments_finance', 'Payments & finance'), ('compliance_contracts', 'Compliance & Contracts'), ('supports', 'Supports'), ('analytics', 'Analytics'), ('messages_monitoring', 'Messages Monitoring'), ('careers', 'Careers'), ('users_management', 'Users Management')], db_index=True, max_length=64),
        ),
    ]
