# Generated by Django 4.2.23 on 2026-04-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_placed", "Order Placed"),
                            ("order_paid", "Order Paid"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_completed", "Order Completed"),
                            ("quote_received", "Quote Received"),
                            ("quote_responded", "Quote Responded"),
                            ("quote_cancelled", "Quote Cancelled"),
                            ("quote_converted", "Quote Converted"),
                            ("new_message", "New Message"),
                            ("new_inquiry", "New Inquiry"),
                            ("inquiry_replied", "Inquiry Replied"),
                            ("new_review", "New Review"),
                            ("payment_success", "Payment Successful"),
                            ("payment_failed", "Payment Failed"),
                            ("payout_processed", "Payout Processed"),
                            ("payout_failed", "Payout Failed"),
                            ("listing_approved", "Listing Approved"),
                            ("listing_rejected", "Listing Rejected"),
                            ("store_verified", "Store Verified"),
                            ("verification_approved", "Verification Approved"),
                            ("verification_rejected", "Verification Rejected"),
                            ("rental_reminder", "Rental Reminder"),
                            ("rental_extended", "Rental Extended"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Frontend route e.g. /orders/123",
                        max_length=500,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, help_text="e.g. 'View Order'", max_length=100
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_2d3764_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_583549_idx",
                    ),
                ],
            },
        ),
    ]
